name: Generate and Deploy Contributors List

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Generate Contributors Images
      uses:  wow-actions/contributors-list@v1
      with:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
          round: true
          userNameHeight: 24
