name: Generate and Deploy Contributors List

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
          submodules: 'true'  
      
    - name: Generate Contributors Images
      uses:  wow-actions/contributors-list@v1
      with:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
          round: true
          userNameHeight: 19

    - name: List build directory
      run: ls -al build  # Debugging step, can be removed later

    - name: Setup Git
      run: |
          git config --global user.name 'Your Name'
          git config --global user.email 'your-email@example.com'

    - name: Deploy SVG to GitHub Pages
      run: |
          git clone --branch=gh-pages https://github.com/${{ github.repository }} gh-pages
          cp build/CONTRIBUTORS.svg gh-pages/
          cd gh-pages
          git add CONTRIBUTORS.svg
          git commit -m "Deploy updated SVG"
          git push origin gh-pages
