name: Generate and Deploy Contributors List

on:
  push:
    branches:
      - master, pranav

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Generate Contributors Images
      uses:  wow-actions/contributors-list@v1
      with:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
          round: true
          userNameHeight: 24

    - name: Generate Collaborators Images
      uses: wow-actions/contributors-list@v1
      with:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
          svgTemplate: >
            <svg
              xmlns="http://www.w3.org/2000/svg"
              xmlns:xlink="http://www.w3.org/1999/xlink"
              version="1.1"
              width="{{ width }}"
              height="{{ collaboratorsHeight }}"
            >
              <style>.contributor-link { cursor: pointer; }</style>
              {{{ collaborators }}}
            </svg>
