name: Generate and Deploy Contributors List

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: wow-actions/contributors-list@v1
      with:
        GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
        svgTemplate: >
          <svg
            xmlns="http://www.w3.org/2000/svg"
            xmlns:xlink="http://www.w3.org/1999/xlink"
            version="1.1"
            width="{{ width }}"
            height="{{ collaboratorsHeight }}"
          >
            <style>.contributor-link { cursor: pointer; }</style>
            {{{ collaborators }}}
          </svg>