name: Generate and Deploy Contributors List

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Generate Contributors Images
      uses:  wow-actions/contributors-list@v1
      with:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
          round: true
          userNameHeight: 19

    - name: Deploy SVG to GitHub Pages
      run: |
        git clone --branch=gh-pages https://github.com/${{ github.repository }} gh-pages
        cp build/CONTRIBUTORS.svg gh-pages/
        touch gh-pages/.nojekyll
        cd gh-pages
        git add CONTRIBUTORS.svg .nojekyll
        git commit -m "Deploy updated SVG"
        git push origin gh-pages
